insert into user_details(id, birth_date, name) values (1001, current_date(), 'Yash')
insert into user_details(id, birth_date, name) values (1002, current_date(), 'Ravi')
insert into user_details(id, birth_date, name) values (1003, current_date(), 'Sunil')
insert into user_details(id, birth_date, name) values (1004, current_date(), 'Anil')
insert into post(id, desc, user_id) values (2001, 'I want to learn java', 1001)
insert into post(id, desc, user_id) values (2003, 'I want to learn MERN', 1001)
insert into post(id, desc, user_id) values (2002, 'I want to learn AWS', 1002)
insert into post(id, desc, user_id) values (2004, 'I want to learn spring', 1002)